import { create } from 'twrnc';
const tw = create({
    // Add your custom styles here
    // Example:
    // container: 'flex bg-white',
    // text: 'text-black',
    // ...
    // ...
    // ...
    // container: 'flex bg-white',
    // text: 'text-black',
    // ...
    // ...
    // ...
});


export default tw;
